<a href="https://colab.research.google.com/github/lavanyamalhotra/PYTHON/blob/main/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## numpy array and basics


In [ ]:
import numpy as np
### creating array from list
arr=np.array([1,2,3,4,5])
print("1D array :",arr)
# Correcting the 2D array to have consistent row lengths
arr2=np.array([[1,2,3],[4,5,6]]) # Added a 6 to the second row
print("2D array :",arr2)

In [ ]:
### list vs numpy array
py_list=[1,2,3]
print("Python list multiplication" , py_list*2)

np_array=np.array([1,2,3]) #element wise multiplication
print("Python list multiplication" , np_array*2)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python list multiplication [2 4 6]


In [ ]:
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List Operation time: ", time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy Operation time: ", time.time()-start)


 List Operation time:  0.11686325073242188

 Numpy Operation time:  0.012328863143920898


In [ ]:
from collections.abc import Sequence
## creating array from scratch
zeroes=np.zeros((3,4))
print("zero array : \n",zeroes)

full=np.full((2,2),7)
print("full array : \n",full)

random = np.random.random((2,3))
print("random array : \n",random)

sequence=np.arange(0,11,2)
print("sequence array : \n",sequence)

zero array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
full array : 
 [[7 7]
 [7 7]]
random array : 
 [[0.3777326  0.35124979 0.66361294]
 [0.13671657 0.22711983 0.2436526 ]]
sequence array : 
 [ 0  2  4  6  8 10]


In [ ]:
## vector matrix and tensor
vector=np.array([1,2,3])
print("Vector : ",vector)

matrix=np.array([[1,2,3],
                [4,5,6]])
print("matrix :",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("tensor array :",tensor)

Vector :  [1 2 3]
matrix : [[1 2 3]
 [4 5 6]]
tensor array : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
### array properties
arr=np.array([[1,2,3],
              [4,5,6]])
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("Data type ",arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Data type  int64


In [ ]:
## array reshaping
arr=np.arange(12)
print("Original array",arr)
reshaped=arr.reshape((3,4))
print("Reshaped \n",reshaped)

flattened=reshaped.flatten()
print("Flattended array",flattened)

#return view instead of copy
raveled=reshaped.ravel()
print("Raveld array",raveled)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattended array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
